### PR TITLE
Use native Object.assign for JSX spread + Babel 7 + .babelrc.js

### PR DESCRIPTION
**Pull request by hzoo**
```js
<A a {...b}/>
```

Turns into

```js
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

React.createElement(A, _extends({ a: true }, b));
```

If you need the `useBuiltIns` option it won't add the inline Object.assign polyfill

In theory, preset-env and all plugins should be able to auto know whether to do this or not. (I'l be trying to work on making this work: https://github.com/babel/notes/blob/master/2017-04/april-08.md#proposed-babel-roadmap. Basically all plugins should be able to query for support in preset-env/targets or the config.

Probably want to use babel-polyfill and useBuiltIns for the fallback polyfills though?

### CODE REVIEW

**Comment by kristoferbaxter** [comment]
I'll work on the fallback implementation next. Thank you for the PR, I learned a ton from it.

**Comment by addyosmani** [comment]
\o/

**Comment by hzoo** [comment]
Still figuring it out (only used on our app since alpha) but you can do `useBuiltIns: "usage"` as an "env" option and then make `babel-polyfill` a dependency https://github.com/babel/babel-preset-env/tree/2.0#usebuiltins

**Comment by NekR** [comment]
@hzoo is there a list of what built-ins Babel may use and in which situations?

**Comment by hzoo** [comment]
the useBuiltIns used in jsx/object-rest is only Object.assign, everything else isn't auto added. Everything else I explain in https://github.com/necolas/react-native-web/issues/409#issuecomment-295057475 (use a polyfill via preset-env or transform-runtime)

**Comment by NekR** [comment]
Thanks!

**Pull request merged**
